/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.CurrencyChain = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The CurrencyChain model module.
   * @module model/CurrencyChain
   */

  /**
   * Constructs a new <code>CurrencyChain</code>.
   * @alias module:model/CurrencyChain
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>CurrencyChain</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrencyChain} obj Optional instance to populate.
   * @return {module:model/CurrencyChain} The populated <code>CurrencyChain</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('chain')) {
        obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
      }
      if (data.hasOwnProperty('name_cn')) {
        obj['name_cn'] = ApiClient.convertToType(data['name_cn'], 'String');
      }
      if (data.hasOwnProperty('name_en')) {
        obj['name_en'] = ApiClient.convertToType(data['name_en'], 'String');
      }
      if (data.hasOwnProperty('is_disabled')) {
        obj['is_disabled'] = ApiClient.convertToType(data['is_disabled'], 'Number');
      }
      if (data.hasOwnProperty('is_deposit_disabled')) {
        obj['is_deposit_disabled'] = ApiClient.convertToType(data['is_deposit_disabled'], 'Number');
      }
      if (data.hasOwnProperty('is_withdraw_disabled')) {
        obj['is_withdraw_disabled'] = ApiClient.convertToType(data['is_withdraw_disabled'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Chain name
   * @member {String} chain
   */
  exports.prototype['chain'] = undefined;
  /**
   * Chain name in Chinese
   * @member {String} name_cn
   */
  exports.prototype['name_cn'] = undefined;
  /**
   * Chain name in English
   * @member {String} name_en
   */
  exports.prototype['name_en'] = undefined;
  /**
   * If it is disabled. 0 means NOT being disabled
   * @member {Number} is_disabled
   */
  exports.prototype['is_disabled'] = undefined;
  /**
   * Is deposit disabled. 0 means not
   * @member {Number} is_deposit_disabled
   */
  exports.prototype['is_deposit_disabled'] = undefined;
  /**
   * Is withdrawal disabled. 0 means not
   * @member {Number} is_withdraw_disabled
   */
  exports.prototype['is_withdraw_disabled'] = undefined;



  return exports;
}));

