/**
 * Gate API v4
 * APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.DepositAddress = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The DepositAddress model module.
   * @module model/DepositAddress
   */

  /**
   * Constructs a new <code>DepositAddress</code>.
   * @alias module:model/DepositAddress
   * @class
   * @param currency {String} Currency detail
   * @param address {String} Deposit address
   */
  var exports = function(currency, address) {
    var _this = this;

    _this['currency'] = currency;
    _this['address'] = address;
  };

  /**
   * Constructs a <code>DepositAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DepositAddress} obj Optional instance to populate.
   * @return {module:model/DepositAddress} The populated <code>DepositAddress</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
    }
    return obj;
  }

  /**
   * Currency detail
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * Deposit address
   * @member {String} address
   */
  exports.prototype['address'] = undefined;



  return exports;
}));

