/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IndexConstituent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IndexConstituent'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.FuturesIndexConstituents = factory(root.GateApi.ApiClient, root.GateApi.IndexConstituent);
  }
}(this, function(ApiClient, IndexConstituent) {
  'use strict';


  /**
   * The FuturesIndexConstituents model module.
   * @module model/FuturesIndexConstituents
   */

  /**
   * Constructs a new <code>FuturesIndexConstituents</code>.
   * @alias module:model/FuturesIndexConstituents
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FuturesIndexConstituents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FuturesIndexConstituents} obj Optional instance to populate.
   * @return {module:model/FuturesIndexConstituents} The populated <code>FuturesIndexConstituents</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('index')) {
        obj['index'] = ApiClient.convertToType(data['index'], 'String');
      }
      if (data.hasOwnProperty('constituents')) {
        obj['constituents'] = ApiClient.convertToType(data['constituents'], [IndexConstituent]);
      }
    }
    return obj;
  }

  /**
   * Index name
   * @member {String} index
   */
  exports.prototype['index'] = undefined;
  /**
   * Constituents
   * @member {Array.<module:model/IndexConstituent>} constituents
   */
  exports.prototype['constituents'] = undefined;



  return exports;
}));

