/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.IndexConstituent = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The IndexConstituent model module.
   * @module model/IndexConstituent
   */

  /**
   * Constructs a new <code>IndexConstituent</code>.
   * @alias module:model/IndexConstituent
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>IndexConstituent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndexConstituent} obj Optional instance to populate.
   * @return {module:model/IndexConstituent} The populated <code>IndexConstituent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('exchange')) {
        obj['exchange'] = ApiClient.convertToType(data['exchange'], 'String');
      }
      if (data.hasOwnProperty('symbols')) {
        obj['symbols'] = ApiClient.convertToType(data['symbols'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Exchange
   * @member {String} exchange
   */
  exports.prototype['exchange'] = undefined;
  /**
   * Symbol list
   * @member {Array.<String>} symbols
   */
  exports.prototype['symbols'] = undefined;



  return exports;
}));

