/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.OptionsUnderlyingTicker = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The OptionsUnderlyingTicker model module.
   * @module model/OptionsUnderlyingTicker
   */

  /**
   * Constructs a new <code>OptionsUnderlyingTicker</code>.
   * Options underlying detail
   * @alias module:model/OptionsUnderlyingTicker
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>OptionsUnderlyingTicker</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptionsUnderlyingTicker} obj Optional instance to populate.
   * @return {module:model/OptionsUnderlyingTicker} The populated <code>OptionsUnderlyingTicker</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('trade_put')) {
        obj['trade_put'] = ApiClient.convertToType(data['trade_put'], 'Number');
      }
      if (data.hasOwnProperty('trade_call')) {
        obj['trade_call'] = ApiClient.convertToType(data['trade_call'], 'Number');
      }
      if (data.hasOwnProperty('index_price')) {
        obj['index_price'] = ApiClient.convertToType(data['index_price'], 'String');
      }
    }
    return obj;
  }

  /**
   * Total put options trades amount in last 24h
   * @member {Number} trade_put
   */
  exports.prototype['trade_put'] = undefined;
  /**
   * Total call options trades amount in last 24h
   * @member {Number} trade_call
   */
  exports.prototype['trade_call'] = undefined;
  /**
   * Index price
   * @member {String} index_price
   */
  exports.prototype['index_price'] = undefined;



  return exports;
}));

