/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.OptionsSettlement = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The OptionsSettlement model module.
   * @module model/OptionsSettlement
   */

  /**
   * Constructs a new <code>OptionsSettlement</code>.
   * @alias module:model/OptionsSettlement
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>OptionsSettlement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptionsSettlement} obj Optional instance to populate.
   * @return {module:model/OptionsSettlement} The populated <code>OptionsSettlement</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Number');
      }
      if (data.hasOwnProperty('contract')) {
        obj['contract'] = ApiClient.convertToType(data['contract'], 'String');
      }
      if (data.hasOwnProperty('profit')) {
        obj['profit'] = ApiClient.convertToType(data['profit'], 'String');
      }
      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'String');
      }
      if (data.hasOwnProperty('strike_price')) {
        obj['strike_price'] = ApiClient.convertToType(data['strike_price'], 'String');
      }
      if (data.hasOwnProperty('settle_price')) {
        obj['settle_price'] = ApiClient.convertToType(data['settle_price'], 'String');
      }
    }
    return obj;
  }

  /**
   * Last changed time of configuration
   * @member {Number} time
   */
  exports.prototype['time'] = undefined;
  /**
   * Contract name
   * @member {String} contract
   */
  exports.prototype['contract'] = undefined;
  /**
   * Settlement profit per size
   * @member {String} profit
   */
  exports.prototype['profit'] = undefined;
  /**
   * Settlement fee per size
   * @member {String} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * Strike price
   * @member {String} strike_price
   */
  exports.prototype['strike_price'] = undefined;
  /**
   * settlement price
   * @member {String} settle_price
   */
  exports.prototype['settle_price'] = undefined;



  return exports;
}));

