/**
 * Gate API v4
 * APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.Repayment = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Repayment model module.
   * @module model/Repayment
   * @version 4.6.0
   */

  /**
   * Constructs a new <code>Repayment</code>.
   * @alias module:model/Repayment
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Repayment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Repayment} obj Optional instance to populate.
   * @return {module:model/Repayment} The populated <code>Repayment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('create_time')) {
        obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
      }
      if (data.hasOwnProperty('principal')) {
        obj['principal'] = ApiClient.convertToType(data['principal'], 'String');
      }
      if (data.hasOwnProperty('interest')) {
        obj['interest'] = ApiClient.convertToType(data['interest'], 'String');
      }
    }
    return obj;
  }

  /**
   * Loan record ID
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Repayment time
   * @member {String} create_time
   */
  exports.prototype['create_time'] = undefined;
  /**
   * Repaid principal
   * @member {String} principal
   */
  exports.prototype['principal'] = undefined;
  /**
   * Repaid interest
   * @member {String} interest
   */
  exports.prototype['interest'] = undefined;



  return exports;
}));


