/**
 * Gate API v4
 * APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.Transfer = factory(root.GateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * The Transfer model module.
   * @module model/Transfer
   */

  /**
   * Constructs a new <code>Transfer</code>.
   * Accounts available to transfer:  - &#x60;spot&#x60;: spot account - &#x60;margin&#x60;: margin account - &#x60;futures&#x60;: perpetual futures account - &#x60;delivery&#x60;: delivery futures account
   * @alias module:model/Transfer
   * @class
   * @param currency {String} Transfer currency. For futures account, `currency` can be set to `POINT` or settle currency
   * @param from {module:model/Transfer.FromEnum} Account transferred from
   * @param to {module:model/Transfer.ToEnum} Account transferred to
   * @param amount {String} Transfer amount
   */
  var exports = function(currency, from, to, amount) {
    var _this = this;

    _this['currency'] = currency;
    _this['from'] = from;
    _this['to'] = to;
    _this['amount'] = amount;
  };

  /**
   * Constructs a <code>Transfer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transfer} obj Optional instance to populate.
   * @return {module:model/Transfer} The populated <code>Transfer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], 'String');
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
      }
      if (data.hasOwnProperty('currency_pair')) {
        obj['currency_pair'] = ApiClient.convertToType(data['currency_pair'], 'String');
      }
      if (data.hasOwnProperty('settle')) {
        obj['settle'] = ApiClient.convertToType(data['settle'], 'String');
      }
    }
    return obj;
  }

  /**
   * Transfer currency. For futures account, `currency` can be set to `POINT` or settle currency
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * Account transferred from
   * @member {module:model/Transfer.FromEnum} from
   */
  exports.prototype['from'] = undefined;
  /**
   * Account transferred to
   * @member {module:model/Transfer.ToEnum} to
   */
  exports.prototype['to'] = undefined;
  /**
   * Transfer amount
   * @member {String} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Margin currency pair. Required if transfer from or to margin account
   * @member {String} currency_pair
   */
  exports.prototype['currency_pair'] = undefined;
  /**
   * Futures settle currency. Required if `currency` is `POINT`
   * @member {String} settle
   */
  exports.prototype['settle'] = undefined;


  /**
   * Allowed values for the <code>from</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FromEnum = {
    /**
     * value: "spot"
     * @const
     */
    "spot": "spot",
    /**
     * value: "margin"
     * @const
     */
    "margin": "margin",
    /**
     * value: "futures"
     * @const
     */
    "futures": "futures",
    /**
     * value: "delivery"
     * @const
     */
    "delivery": "delivery"  };

  /**
   * Allowed values for the <code>to</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ToEnum = {
    /**
     * value: "spot"
     * @const
     */
    "spot": "spot",
    /**
     * value: "margin"
     * @const
     */
    "margin": "margin",
    /**
     * value: "futures"
     * @const
     */
    "futures": "futures",
    /**
     * value: "delivery"
     * @const
     */
    "delivery": "delivery"  };


  return exports;
}));

