/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlashSwapCurrency'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/FlashSwapCurrency'));
  } else {
    // Browser globals (root is window)
    if (!root.GateApi) {
      root.GateApi = {};
    }
    root.GateApi.FlashSwapApi = factory(root.GateApi.ApiClient, root.GateApi.FlashSwapCurrency);
  }
}(this, function(ApiClient, FlashSwapCurrency) {
  'use strict';

  /**
   * FlashSwap service.
   * @module api/FlashSwapApi
   */

  /**
   * Constructs a new FlashSwapApi. 
   * @alias module:api/FlashSwapApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the listFlashSwapCurrencies operation.
     * @callback module:api/FlashSwapApi~listFlashSwapCurrenciesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/FlashSwapCurrency>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all supported currencies in flash swap
     * @param {module:api/FlashSwapApi~listFlashSwapCurrenciesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/FlashSwapCurrency>}
     */
    this.listFlashSwapCurrencies = function(callback) {
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [FlashSwapCurrency];
      return this.apiClient.callApi(
        '/flash_swap/currencies', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
